### ISSUE TITLE
undefined method `casecmp?' for nil:NilClass -> missing commit on ruby gems

### ISSUE THREAD

**Issue by chackl1990** [Kilobyte22/webrick-websocket#5]
Hi!
If i do "gem install webrick-websocket" it will install "webrick-websocket-0.0.3"

It seems that this commit is missing:
https://github.com/Kilobyte22/webrick-websocket/commit/f95ae8e2f995b269afd2ec00239bb35cd56b1542

happens on a fresh pulled docker with ruby:latest

test:
```
server.mount_proc '/test' do |request, response|
    response.status = 200
    response['Content-Type'] = 'text/plain'
    response.body = 'Hello, World!'
end
```

getting "/test" will result in "ERROR NoMethodError: undefined method `casecmp?' for nil:NilClass"

when getting the server.rb from github it works.

kind thanks!

**Comment by yogo1212** [comment]
i can confirm.
the 'review changes' page from rubygems shows the latest changes and doesn't include the ` || ''`.

**Comment by Kilobyte22** [comment]
I believe i never actually published that, i'll have to see if i can get that working.

**Comment by Kilobyte22** [comment]
@yogo1212 Should be live on rubygems as v0.0.4. If it's not working please reply again.
